from functools import wraps

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.urls import path

from .functions_view import api, badges, basel_scores_form, credit_scoreshits, creditscorecreate, customers, dashboard, email, ifrs9_results, scorecard_historical_scores, ifrs9_score_config, ifrs9_scores_form, ifrs9_supporting_data, maker_checker, media, notifications, settings, template_maker_checker, uploads
from .permission_catalog import ROUTE_PERMISSION_MAP

app_name = "scorecard"


def _user_has_route_permission(user, permission_code=None):
    if not permission_code:
        return True
    if getattr(user, "is_superuser", False):
        return True
    if isinstance(permission_code, (list, tuple, set)):
        return any(user.has_perm(code) for code in permission_code)
    return user.has_perm(permission_code)


def _route_permission_required(permission_code):
    def decorator(callback):
        @wraps(callback)
        def wrapped(request, *args, **kwargs):
            if not _user_has_route_permission(request.user, permission_code):
                raise PermissionDenied("You do not have permission to access this scorecard page.")
            return callback(request, *args, **kwargs)

        return wrapped

    return decorator


def _secure_callback(callback, permission_code=None):
    if permission_code:
        callback = _route_permission_required(permission_code)(callback)
    wrapped = login_required(callback)
    return wrapped


def _protect_urlpatterns(patterns):
    protected = []
    for pattern in patterns:
        protected.append(
            path(
                pattern.pattern._route,
                _secure_callback(pattern.callback, ROUTE_PERMISSION_MAP.get(pattern.name)),
                kwargs=pattern.default_args,
                name=pattern.name,
            )
        )
    return protected

urlpatterns = [
    path("badges/counts/", badges.badge_counts_view, name="badge_counts"),
    # Dashboard
    path(
        "switch-branch/",
        customers.switch_branch_view,
        name="switch_branch",
    ),
    path(
        "scorecard_dashboard/",
        dashboard.dashboard_view,
        name="scorecard_dashboard",
    ),
    path(
        "scorecard_dashboard/content/",
        dashboard.dashboard_content_view,
        name="scorecard_dashboard_content",
    ),
    path(
        "api/",
        api.api_dashboard_view,
        name="api_dashboard",
    ),
    path(
        "api/settings/",
        api.api_settings_view,
        name="api_settings",
    ),
    path(
        "api/automation/",
        api.api_scheduler_view,
        name="api_scheduler",
    ),
    path(
        "api/automation/status/",
        api.api_scheduler_status_view,
        name="api_scheduler_status",
    ),
    path(
        "api/automation/start/",
        api.api_scheduler_start_view,
        name="api_scheduler_start",
    ),
    path(
        "api/automation/controls/",
        api.api_scheduler_control_view,
        name="api_scheduler_controls",
    ),
    path(
        "api/automation/<int:schedule_id>/toggle/",
        api.api_scheduler_toggle_view,
        name="api_scheduler_toggle",
    ),
    path(
        "api/automation/<int:schedule_id>/run-now/",
        api.api_scheduler_run_now_view,
        name="api_scheduler_run_now",
    ),
    path(
        "api/main-sync/",
        api.api_main_sync_view,
        name="api_main_sync",
    ),
    path(
        "api/main-sync/<str:reporting_date_value>/run/",
        api.api_main_sync_run_view,
        name="api_main_sync_run",
    ),
    path(
        "api/automation/<int:schedule_id>/delete/",
        api.api_scheduler_delete_view,
        name="api_scheduler_delete",
    ),
    path(
        "api/endpoints/",
        api.api_endpoints_view,
        name="api_endpoints",
    ),
    path(
        "api/health/",
        api.api_health_view,
        name="api_health",
    ),
    path(
        "api/endpoints/test/",
        api.api_endpoint_test_view,
        name="api_endpoint_test",
    ),
    path(
        "api/endpoints/save/",
        api.api_endpoint_save_view,
        name="api_endpoint_save",
    ),
    path(
        "api/endpoints/<int:endpoint_id>/delete/",
        api.api_endpoint_delete_view,
        name="api_endpoint_delete",
    ),
    path(
        "api/retrieve/",
        api.api_retrieve_view,
        name="api_retrieve",
    ),
    path(
        "api/import/",
        api.api_import_view,
        name="api_import",
    ),
    path(
        "api/import/run/",
        api.api_import_run_view,
        name="api_import_run",
    ),
    path(
        "api/import/progress/",
        api.api_import_progress_view,
        name="api_import_progress",
    ),
    path(
        "api/import/<int:run_id>/stop/",
        api.api_import_stop_view,
        name="api_import_stop",
    ),
    path(
        "api/import/<int:run_id>/retry/",
        api.api_import_retry_view,
        name="api_import_retry",
    ),
    path(
        "imports/",
        uploads.upload_home_view,
        name="upload_home",
    ),
    path(
        "imports/<str:upload_kind>/",
        uploads.upload_start_view,
        name="upload_start",
    ),
    path(
        "imports/<str:upload_kind>/mapping/",
        uploads.upload_mapping_view,
        name="upload_mapping",
    ),
    path(
        "imports/<str:upload_kind>/preview/",
        uploads.upload_preview_view,
        name="upload_preview",
    ),
    path(
        "imports/<str:upload_kind>/preview/download/",
        uploads.upload_preview_full_download_view,
        name="upload_preview_full_download",
    ),
    path(
        "imports/<str:upload_kind>/preview/errors/download/",
        uploads.upload_preview_errors_download_view,
        name="upload_preview_errors_download",
    ),
    path(
        "imports/<str:upload_kind>/result/",
        uploads.upload_result_view,
        name="upload_result",
    ),
    path(
        "imports/<str:upload_kind>/run/",
        uploads.upload_run_view,
        name="upload_run",
    ),
    path(
        "imports/<str:upload_kind>/reset/",
        uploads.upload_reset_view,
        name="upload_reset",
    ),
    # Basel template configuration (frontend)
    path(
        "basel/templates/",
        credit_scoreshits.basel_template_list_view,
        name="basel_template_list",
    ),
    path(
        "basel/templates/new/",
        credit_scoreshits.basel_template_create_new_view,
        name="basel_template_create",
    ),
    path(
        "basel/templates/<int:template_id>/",
        credit_scoreshits.basel_template_detail_view,
        name="basel_template_detail",
    ),
    path(
        "basel/templates/<int:template_id>/builder/",
        creditscorecreate.basel_template_builder_view,
        name="basel_template_builder",
    ),
    path(
        "basel/templates/<int:template_id>/edit/",
        credit_scoreshits.basel_template_edit_view,
        name="basel_template_edit",
    ),
    path(
        "basel/templates/<int:template_id>/delete/",
        credit_scoreshits.basel_template_delete_view,
        name="basel_template_delete",
    ),
    path(
        "basel/templates/<int:template_id>/options/<int:option_id>/edit/",
        credit_scoreshits.option_edit_view,
        name="option_edit",
    ),
    path(
        "basel/templates/<int:template_id>/grade-bands/",
        credit_scoreshits.grade_band_list_view,
        name="grade_band_list",
    ),
    path(
        "basel/templates/<int:template_id>/grade-bands/new/",
        credit_scoreshits.grade_band_create_view,
        name="grade_band_create",
    ),
    path(
        "basel/templates/<int:template_id>/grade-bands/<int:band_id>/edit/",
        credit_scoreshits.grade_band_edit_view,
        name="grade_band_edit",
    ),
    path(
        "basel/templates/<int:template_id>/grade-bands/<int:band_id>/delete/",
        credit_scoreshits.grade_band_delete_view,
        name="grade_band_delete",
    ),
    # Section management
    path(
        "basel/templates/<int:template_id>/sections/",
        creditscorecreate.section_list_view,
        name="section_list",
    ),
    path(
        "basel/templates/<int:template_id>/sections/new/",
        creditscorecreate.section_create_view,
        name="section_create",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/edit/",
        creditscorecreate.section_edit_view,
        name="section_edit",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/delete/",
        creditscorecreate.section_delete_view,
        name="section_delete",
    ),
    # Risk driver management
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/",
        creditscorecreate.risk_driver_list_view,
        name="risk_driver_list",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/new/",
        creditscorecreate.risk_driver_create_view,
        name="risk_driver_create",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/edit/",
        creditscorecreate.risk_driver_edit_view,
        name="risk_driver_edit",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/delete/",
        creditscorecreate.risk_driver_delete_view,
        name="risk_driver_delete",
    ),
    # Attribute management
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/",
        creditscorecreate.attribute_list_view,
        name="attribute_list",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/new/",
        creditscorecreate.attribute_create_view,
        name="attribute_create",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/edit/",
        creditscorecreate.attribute_edit_view,
        name="attribute_edit",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/delete/",
        creditscorecreate.attribute_delete_view,
        name="attribute_delete",
    ),
    # Option management
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/",
        creditscorecreate.option_list_view,
        name="option_list",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/new/",
        creditscorecreate.option_create_view,
        name="option_create",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/<int:option_id>/edit/",
        creditscorecreate.option_edit_view,
        name="option_edit_new",
    ),
    path(
        "basel/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/<int:option_id>/delete/",
        creditscorecreate.option_delete_view,
        name="option_delete",
    ),
    # IFRS9 template configuration (frontend)
    path(
        "ifrs9/templates/",
        ifrs9_score_config.ifrs9_template_list_view,
        name="ifrs9_template_list",
    ),
    path(
        "ifrs9/templates/new/",
        ifrs9_score_config.ifrs9_template_create_view,
        name="ifrs9_template_create",
    ),
    path(
        "ifrs9/templates/<int:template_id>/",
        ifrs9_score_config.ifrs9_template_detail_view,
        name="ifrs9_template_detail",
    ),
    path(
        "ifrs9/templates/<int:template_id>/builder/",
        ifrs9_score_config.ifrs9_template_builder_view,
        name="ifrs9_template_builder",
    ),
    path(
        "ifrs9/templates/<int:template_id>/edit/",
        ifrs9_score_config.ifrs9_template_edit_view,
        name="ifrs9_template_edit",
    ),
    path(
        "ifrs9/templates/<int:template_id>/delete/",
        ifrs9_score_config.ifrs9_template_delete_view,
        name="ifrs9_template_delete",
    ),
    path(
        "ifrs9/templates/<int:template_id>/grade-bands/",
        ifrs9_score_config.ifrs9_grade_band_list_view,
        name="ifrs9_grade_band_list",
    ),
    path(
        "ifrs9/templates/<int:template_id>/grade-bands/new/",
        ifrs9_score_config.ifrs9_grade_band_create_view,
        name="ifrs9_grade_band_create",
    ),
    path(
        "ifrs9/templates/<int:template_id>/grade-bands/<int:band_id>/edit/",
        ifrs9_score_config.ifrs9_grade_band_edit_view,
        name="ifrs9_grade_band_edit",
    ),
    path(
        "ifrs9/templates/<int:template_id>/grade-bands/<int:band_id>/delete/",
        ifrs9_score_config.ifrs9_grade_band_delete_view,
        name="ifrs9_grade_band_delete",
    ),
    # IFRS9 Section management
    path(
        "ifrs9/templates/<int:template_id>/sections/",
        ifrs9_score_config.ifrs9_section_list_view,
        name="ifrs9_section_list",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/new/",
        ifrs9_score_config.ifrs9_section_create_view,
        name="ifrs9_section_create",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/edit/",
        ifrs9_score_config.ifrs9_section_edit_view,
        name="ifrs9_section_edit",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/delete/",
        ifrs9_score_config.ifrs9_section_delete_view,
        name="ifrs9_section_delete",
    ),
    # IFRS9 Risk driver management
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/",
        ifrs9_score_config.ifrs9_risk_driver_list_view,
        name="ifrs9_risk_driver_list",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/new/",
        ifrs9_score_config.ifrs9_risk_driver_create_view,
        name="ifrs9_risk_driver_create",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/edit/",
        ifrs9_score_config.ifrs9_risk_driver_edit_view,
        name="ifrs9_risk_driver_edit",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/delete/",
        ifrs9_score_config.ifrs9_risk_driver_delete_view,
        name="ifrs9_risk_driver_delete",
    ),
    # IFRS9 Attribute management
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/",
        ifrs9_score_config.ifrs9_attribute_list_view,
        name="ifrs9_attribute_list",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/new/",
        ifrs9_score_config.ifrs9_attribute_create_view,
        name="ifrs9_attribute_create",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/edit/",
        ifrs9_score_config.ifrs9_attribute_edit_view,
        name="ifrs9_attribute_edit",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/delete/",
        ifrs9_score_config.ifrs9_attribute_delete_view,
        name="ifrs9_attribute_delete",
    ),
    # IFRS9 Option management
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/",
        ifrs9_score_config.ifrs9_option_list_view,
        name="ifrs9_option_list",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/new/",
        ifrs9_score_config.ifrs9_option_create_view,
        name="ifrs9_option_create",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/<int:option_id>/edit/",
        ifrs9_score_config.ifrs9_option_edit_view,
        name="ifrs9_option_edit",
    ),
    path(
        "ifrs9/templates/<int:template_id>/sections/<int:section_id>/drivers/<int:driver_id>/attributes/<int:attribute_id>/options/<int:option_id>/delete/",
        ifrs9_score_config.ifrs9_option_delete_view,
        name="ifrs9_option_delete",
    ),
    # Farmers credit score evaluation
    path(
        "farmers-credit-score/",
        credit_scoreshits.farmers_credit_scoresheet_view,
        name="farmers_credit_scoresheet",
    ),
    # Basel scores (credit score) system
    path(
        "basel-scores/",
        basel_scores_form.basel_scores_template_select_view,
        name="basel_scores_template_select",
    ),
    path(
        "basel-scores/api/customer-search/",
        basel_scores_form.customer_search_api,
        name="basel_scores_customer_search",
    ),
    path(
        "basel-scores/<int:template_id>/autofill/",
        basel_scores_form.basel_autofill_api,
        name="basel_scores_autofill",
    ),
    path(
        "basel-scores/<int:template_id>/",
        basel_scores_form.basel_scores_form_view,
        name="basel_scores_form",
    ),
    path(
        "basel-scores/submitted/",
        basel_scores_form.basel_scores_submitted_list_view,
        name="basel_scores_submitted_list",
    ),
    path(
        "basel-scores/<int:evaluation_id>/override-grade/",
        basel_scores_form.basel_score_override_grade_view,
        name="basel_scores_override_grade",
    ),
    path(
        "basel-scores/drafts/",
        basel_scores_form.basel_scores_draft_list_view,
        name="basel_scores_draft_list",
    ),
    path(
        "basel-scores/edit/<int:evaluation_id>/",
        basel_scores_form.basel_scores_edit_view,
        name="basel_scores_edit",
    ),
    path(
        "basel-scores/template/<int:evaluation_id>/",
        basel_scores_form.basel_scores_template_assignment_view,
        name="basel_scores_template_assignment",
    ),
    path(
        "basel-scores/view/<int:evaluation_id>/",
        basel_scores_form.basel_scores_view_detail,
        name="basel_scores_view_detail",
    ),
    path(
        "basel-scores/compare/<int:evaluation_id>/",
        basel_scores_form.basel_scores_compare_versions,
        name="basel_scores_compare_versions",
    ),
    path(
        "basel-scores/delete/<int:evaluation_id>/",
        basel_scores_form.basel_scores_delete_view,
        name="basel_scores_delete",
    ),
    path(
        "basel-scores/customer-versions/",
        basel_scores_form.customer_versions_list_view,
        name="basel_scores_customer_versions_list",
    ),
    path(
        "basel-scores/customer-evaluation/<int:evaluation_id>/versions/",
        basel_scores_form.customer_evaluation_versions_view,
        name="basel_scores_customer_evaluation_versions",
    ),
    path(
        "basel-scores/version/<int:version_id>/detail/",
        basel_scores_form.customer_version_detail_view,
        name="basel_scores_customer_version_detail",
    ),
    path(
        "basel-scores/check-existing/",
        basel_scores_form.basel_scores_check_existing,
        name="basel_scores_check_existing",
    ),
    path(
        "basel-scores/export/excel/",
        basel_scores_form.basel_scores_export_excel,
        name="basel_scores_export_excel",
    ),
    path(
        "basel-scores/export/csv/",
        basel_scores_form.basel_scores_export_csv,
        name="basel_scores_export_csv",
    ),
    # IFRS9 Score Form system
    path(
        "ifrs9-scores/",
        ifrs9_scores_form.ifrs9_scores_template_select_view,
        name="ifrs9_scores_template_select",
    ),
    path(
        "ifrs9-scores/api/customer-search/",
        ifrs9_scores_form.customer_search_api,
        name="ifrs9_scores_customer_search",
    ),
    path(
        "ifrs9-scores/<int:template_id>/autofill/",
        ifrs9_scores_form.ifrs9_autofill_api,
        name="ifrs9_scores_autofill",
    ),
    path(
        "ifrs9-scores/<int:template_id>/",
        ifrs9_scores_form.ifrs9_scores_form_view,
        name="ifrs9_scores_form",
    ),
    path(
        "ifrs9-scores/submitted/",
        ifrs9_scores_form.ifrs9_scores_submitted_list_view,
        name="ifrs9_scores_submitted_list",
    ),
    path(
        "ifrs9-scores/drafts/",
        ifrs9_scores_form.ifrs9_scores_draft_list_view,
        name="ifrs9_scores_draft_list",
    ),
    path(
        "ifrs9-scores/edit/<int:evaluation_id>/",
        ifrs9_scores_form.ifrs9_scores_edit_view,
        name="ifrs9_scores_edit",
    ),
    path(
        "ifrs9-scores/template/<int:evaluation_id>/",
        ifrs9_scores_form.ifrs9_scores_template_assignment_view,
        name="ifrs9_scores_template_assignment",
    ),
    path(
        "ifrs9-scores/view/<int:evaluation_id>/",
        ifrs9_scores_form.ifrs9_scores_view_detail,
        name="ifrs9_scores_view_detail",
    ),
    path(
        "ifrs9-scores/compare/<int:evaluation_id>/",
        ifrs9_scores_form.ifrs9_scores_compare_versions,
        name="ifrs9_scores_compare_versions",
    ),
    path(
        "ifrs9-scores/delete/<int:evaluation_id>/",
        ifrs9_scores_form.ifrs9_scores_delete_view,
        name="ifrs9_scores_delete",
    ),
    path(
        "ifrs9-scores/customer-versions/",
        ifrs9_scores_form.ifrs9_customer_versions_list_view,
        name="ifrs9_customer_versions_list",
    ),
    path(
        "ifrs9-scores/customer-evaluation/<int:evaluation_id>/versions/",
        ifrs9_scores_form.ifrs9_customer_evaluation_versions_view,
        name="ifrs9_customer_evaluation_versions",
    ),
    path(
        "ifrs9-scores/version/<int:version_id>/detail/",
        ifrs9_scores_form.ifrs9_customer_version_detail_view,
        name="ifrs9_customer_version_detail",
    ),
    path(
        "ifrs9-scores/check-existing/",
        ifrs9_scores_form.ifrs9_scores_check_existing,
        name="ifrs9_scores_check_existing",
    ),
    path(
        "ifrs9-scores/export/excel/",
        ifrs9_scores_form.ifrs9_scores_export_excel,
        name="ifrs9_scores_export_excel",
    ),
    path(
        "ifrs9-scores/export/csv/",
        ifrs9_scores_form.ifrs9_scores_export_csv,
        name="ifrs9_scores_export_csv",
    ),
    # Customer URLs
    path(
        "customers/",
        customers.customer_list_view,
        name="customer_list",
    ),
    path(
        "customers/<int:customer_id>/detail/",
        customers.customer_detail_view,
        name="customer_detail",
    ),
    path(
        "customers/export/excel/",
        customers.customer_export_excel,
        name="customer_export_excel",
    ),
    path(
        "customers/export/csv/",
        customers.customer_export_csv,
        name="customer_export_csv",
    ),
    path(
        "customers/without-questionnaires/",
        customers.customer_without_questionnaire_list_view,
        name="customer_without_questionnaire_list",
    ),
    path(
        "customers/without-questionnaires/export/excel/",
        customers.customer_without_questionnaire_export_excel,
        name="customer_without_questionnaire_export_excel",
    ),
    path(
        "customers/without-questionnaires/export/csv/",
        customers.customer_without_questionnaire_export_csv,
        name="customer_without_questionnaire_export_csv",
    ),
    path(
        "customers/without-ifrs9/",
        customers.customer_without_ifrs9_list_view,
        name="customer_without_ifrs9_list",
    ),
    path(
        "customers/without-ifrs9/export/excel/",
        customers.customer_without_ifrs9_export_excel,
        name="customer_without_ifrs9_export_excel",
    ),
    path(
        "customers/without-ifrs9/export/csv/",
        customers.customer_without_ifrs9_export_csv,
        name="customer_without_ifrs9_export_csv",
    ),
    path(
        "customers/add/",
        customers.add_customer_view,
        name="add_customer",
    ),
    path(
        "customers/overdraft/",
        customers.manual_overdraft_customer_list_view,
        name="manual_overdraft_customer_list",
    ),
    path(
        "notifications/",
        notifications.notification_list_view,
        name="notifications",
    ),
    path(
        "notifications/<int:notification_id>/read/",
        notifications.notification_mark_read_view,
        name="notification_mark_read",
    ),
    path(
        "notifications/<int:notification_id>/detail/",
        notifications.notification_detail_view,
        name="notification_detail",
    ),
    path(
        "notifications/read-all/",
        notifications.notification_mark_all_read_view,
        name="notification_mark_all_read",
    ),
    path(
        "branches/master/",
        customers.branch_master_view,
        name="branch_master",
    ),
    path(
        "branches/master/sync-from-main-customer/",
        customers.branch_master_sync_from_main_customer_view,
        name="branch_master_sync_from_main_customer",
    ),
    path(
        "email/configuration/",
        email.email_configuration_view,
        name="email_configuration",
    ),
    path(
        "email/templates/",
        email.email_templates_view,
        name="email_templates",
    ),
    path(
        "email/delivery/",
        email.email_delivery_view,
        name="email_delivery",
    ),
    path(
        "settings/permissions/",
        settings.settings_dashboard,
        name="settings_permissions",
    ),
    path(
        "settings/permissions/users/",
        settings.settings_user_roles,
        name="settings_user_roles",
    ),
    path(
        "settings/permissions/users/<int:user_id>/summary/",
        settings.settings_user_access_summary,
        name="settings_user_access_summary",
    ),
    path(
        "settings/permissions/users/<int:user_id>/",
        settings.settings_user_role_assignment,
        name="settings_user_role_assignment",
    ),
    path(
        "settings/permissions/matrix/",
        settings.settings_permission_matrix,
        name="settings_permission_matrix",
    ),
    path(
        "settings/workflow/",
        settings.settings_workflow_approvals,
        name="settings_workflow_approvals",
    ),
    path(
        "settings/permissions/audit/",
        settings.settings_audit_trail,
        name="settings_audit_trail",
    ),
    path(
        "branches/master/<int:branch_id>/delete/",
        customers.branch_master_delete_view,
        name="branch_master_delete",
    ),
    # Documents Management - Questionnaire Documents
    path(
        "scorecard/documents/",
        media.document_list_view,
        name="document_list",
    ),
    path(
        "scorecard/documents/<int:document_id>/",
        media.document_detail_view,
        name="document_detail",
    ),
    path(
        "scorecard/documents/ifrs9/<int:document_id>/",
        media.document_ifrs9_detail_view,
        name="document_ifrs9_detail",
    ),
    path(
        "scorecard/documents/<int:document_id>/delete/",
        media.document_delete_view,
        name="document_delete",
    ),
    path(
        "scorecard/documents/ifrs9/<int:document_id>/delete/",
        media.document_ifrs9_delete_view,
        name="document_ifrs9_delete",
    ),
    # Scorecard Documents Management
    path(
        "scorecard/documents/scorecard/",
        media.scorecard_document_list_view,
        name="scorecard_document_list",
    ),
    path(
        "scorecard/documents/scorecard/upload/",
        media.scorecard_document_upload_view,
        name="scorecard_document_upload",
    ),
    path(
        "scorecard/documents/scorecard/<int:document_id>/",
        media.scorecard_document_detail_view,
        name="scorecard_document_detail",
    ),
    path(
        "scorecard/documents/scorecard/<int:document_id>/download/",
        media.scorecard_document_download_view,
        name="scorecard_document_download",
    ),
    path(
        "scorecard/documents/scorecard/<int:document_id>/delete/",
        media.scorecard_document_delete_view,
        name="scorecard_document_delete",
    ),
    # Maker-Checker Workflow URLs
    # Maker URLs
    path(
        "maker/drafts/",
        maker_checker.maker_draft_list_view,
        name="maker_draft_list",
    ),
    path(
        "maker/submitted/",
        maker_checker.maker_submitted_list_view,
        name="maker_submitted_list",
    ),
    path(
        "maker/basel-scores/view/<int:evaluation_id>/",
        maker_checker.maker_basel_scores_view,
        name="maker_basel_scores_view",
    ),
    path(
        "maker/submit/<int:evaluation_id>/",
        maker_checker.submit_for_review_view,
        name="submit_for_review",
    ),
    path(
        "maker/withdraw/<int:evaluation_id>/",
        maker_checker.withdraw_submission_view,
        name="withdraw_submission",
    ),
    # Checker URLs
    path(
        "checker/pending/",
        maker_checker.checker_pending_list_view,
        name="checker_pending_list",
    ),
    path(
        "checker/my-approvals/",
        maker_checker.checker_my_approvals_view,
        name="checker_my_approvals",
    ),
    path(
        "checker/my-approvals/basel-score/<int:evaluation_id>/",
        basel_scores_form.questionnaire_view_detail,
        name="checker_my_approvals_basel_score_view",
    ),
    path(
        "checker/my-approvals/ifrs9-score/<int:evaluation_id>/",
        ifrs9_scores_form.ifrs9_scores_view_detail,
        name="checker_my_approvals_ifrs9_score_view",
    ),
    path(
        "checker/my-approvals/basel-template/<int:template_id>/",
        credit_scoreshits.basel_template_detail_view,
        name="checker_my_approvals_basel_template_view",
    ),
    path(
        "checker/my-approvals/ifrs9-template/<int:template_id>/",
        ifrs9_score_config.ifrs9_template_detail_view,
        name="checker_my_approvals_ifrs9_template_view",
    ),
    path(
        "checker/review/<int:evaluation_id>/",
        maker_checker.checker_review_view,
        name="checker_review",
    ),
    path(
        "checker/approve/<int:evaluation_id>/",
        maker_checker.approve_evaluation_view,
        name="approve_evaluation",
    ),
    path(
        "checker/return/<int:evaluation_id>/",
        maker_checker.return_evaluation_view,
        name="return_evaluation",
    ),
    # Admin URLs
    path(
        "admin/reopen/<int:evaluation_id>/",
        maker_checker.admin_reopen_view,
        name="admin_reopen",
    ),
    # IFRS9 Maker-Checker Workflow URLs
    # IFRS9 Maker URLs
    path(
        "maker/ifrs9-scores/drafts/",
        maker_checker.maker_ifrs9_scores_draft_list_view,
        name="maker_ifrs9_scores_draft_list",
    ),
    path(
        "maker/ifrs9-scores/submitted/",
        maker_checker.maker_ifrs9_scores_submitted_list_view,
        name="maker_ifrs9_scores_submitted_list",
    ),
    path(
        "maker/ifrs9-scores/view/<int:evaluation_id>/",
        maker_checker.maker_ifrs9_scores_view,
        name="maker_ifrs9_scores_view",
    ),
    path(
        "maker/ifrs9-scores/submit/<int:evaluation_id>/",
        maker_checker.submit_ifrs9_scores_for_review_view,
        name="submit_ifrs9_scores_for_review",
    ),
    path(
        "maker/ifrs9-scores/withdraw/<int:evaluation_id>/",
        maker_checker.withdraw_ifrs9_scores_submission_view,
        name="withdraw_ifrs9_scores_submission",
    ),
    # IFRS9 Checker URLs
    path(
        "checker/ifrs9-scores/pending/",
        maker_checker.checker_ifrs9_scores_pending_list_view,
        name="checker_ifrs9_scores_pending_list",
    ),
    path(
        "checker/ifrs9-scores/review/<int:evaluation_id>/",
        maker_checker.checker_ifrs9_scores_review_view,
        name="checker_ifrs9_scores_review",
    ),
    path(
        "checker/ifrs9-scores/approve/<int:evaluation_id>/",
        maker_checker.approve_ifrs9_scores_evaluation_view,
        name="ifrs9_scores_approve_evaluation",
    ),
    path(
        "checker/ifrs9-scores/return/<int:evaluation_id>/",
        maker_checker.return_ifrs9_scores_evaluation_view,
        name="ifrs9_scores_return_evaluation",
    ),
    # IFRS9 Admin URLs
    path(
        "admin/ifrs9-scores/reopen/<int:evaluation_id>/",
        maker_checker.admin_reopen_ifrs9_scores_view,
        name="admin_reopen_ifrs9_scores",
    ),
    path(
        "checker/ifrs9-supporting-data/",
        ifrs9_supporting_data.ifrs9_supporting_data_view,
        name="ifrs9_supporting_data",
    ),
    path(
        "checker/ifrs9-supporting-data/collateral/",
        ifrs9_supporting_data.ifrs9_supporting_data_collateral_list_view,
        name="ifrs9_supporting_data_collateral",
    ),
    path(
        "checker/ifrs9-supporting-data/collateral/add/",
        ifrs9_supporting_data.ifrs9_supporting_data_collateral_add_view,
        name="ifrs9_supporting_data_collateral_add",
    ),
    path(
        "checker/ifrs9-supporting-data/collateral/<int:record_id>/edit/",
        ifrs9_supporting_data.ifrs9_supporting_data_collateral_edit_view,
        name="ifrs9_supporting_data_collateral_edit",
    ),
    path(
        "checker/ifrs9-supporting-data/collateral/<int:record_id>/delete/",
        ifrs9_supporting_data.ifrs9_supporting_data_collateral_delete_view,
        name="ifrs9_supporting_data_collateral_delete",
    ),
    path(
        "checker/ifrs9-supporting-data/collateral/template/",
        ifrs9_supporting_data.ifrs9_supporting_data_collateral_template_view,
        name="ifrs9_supporting_data_collateral_template",
    ),
    path(
        "checker/ifrs9-supporting-data/payment-schedules/",
        ifrs9_supporting_data.ifrs9_supporting_data_payment_schedule_list_view,
        name="ifrs9_supporting_data_payment_schedules",
    ),
    path(
        "checker/ifrs9-supporting-data/payment-schedules/add/",
        ifrs9_supporting_data.ifrs9_supporting_data_payment_schedule_add_view,
        name="ifrs9_supporting_data_payment_schedules_add",
    ),
    path(
        "checker/ifrs9-supporting-data/payment-schedules/<int:record_id>/edit/",
        ifrs9_supporting_data.ifrs9_supporting_data_payment_schedule_edit_view,
        name="ifrs9_supporting_data_payment_schedules_edit",
    ),
    path(
        "checker/ifrs9-supporting-data/payment-schedules/<int:record_id>/delete/",
        ifrs9_supporting_data.ifrs9_supporting_data_payment_schedule_delete_view,
        name="ifrs9_supporting_data_payment_schedules_delete",
    ),
    path(
        "checker/ifrs9-supporting-data/payment-schedules/template/",
        ifrs9_supporting_data.ifrs9_supporting_data_payment_schedule_template_view,
        name="ifrs9_supporting_data_payment_schedules_template",
    ),
    path(
        "historical-scores/",
        scorecard_historical_scores.historical_scores_list_view,
        name="historical_scores_list",
    ),
    path(
        "historical-scores/download/",
        scorecard_historical_scores.historical_scores_download_view,
        name="historical_scores_download",
    ),
    path(
        "historical-scores/refresh/",
        scorecard_historical_scores.historical_scores_refresh_view,
        name="historical_scores_refresh",
    ),
    path(
        "historical-scores/delete-filtered/",
        scorecard_historical_scores.historical_scores_bulk_delete_view,
        name="historical_scores_bulk_delete",
    ),
    path(
        "ifrs9-results/",
        ifrs9_results.ifrs9_results_home_view,
        name="ifrs9_results_home",
    ),
    path(
        "ifrs9-results/results-extract/",
        ifrs9_results.ifrs9_results_extract_view,
        name="ifrs9_results_extract",
    ),
    path(
        "ifrs9-results/results-extract/download/",
        ifrs9_results.ifrs9_results_extract_download_view,
        name="ifrs9_results_extract_download",
    ),
    path(
        "ifrs9-results/ecl-summary/",
        ifrs9_results.ifrs9_results_ecl_summary_view,
        name="ifrs9_results_ecl_summary",
    ),
    path(
        "ifrs9-results/ecl-summary/download/excel/",
        ifrs9_results.ifrs9_results_ecl_summary_download_excel_view,
        name="ifrs9_results_ecl_summary_download_excel",
    ),
    path(
        "ifrs9-results/ecl-summary/download/pdf/",
        ifrs9_results.ifrs9_results_ecl_summary_download_pdf_view,
        name="ifrs9_results_ecl_summary_download_pdf",
    ),
    # Template Maker URLs
    path(
        "maker/templates/drafts/",
        template_maker_checker.template_maker_draft_list_view,
        name="template_maker_draft_list",
    ),
    path(
        "maker/templates/submitted/",
        template_maker_checker.template_maker_submitted_list_view,
        name="template_maker_submitted_list",
    ),
    path(
        "maker/template/view/<int:template_id>/",
        template_maker_checker.template_maker_view,
        name="template_maker_view",
    ),
    path(
        "maker/template/submit/<int:template_id>/",
        template_maker_checker.template_submit_view,
        name="template_submit",
    ),
    path(
        "maker/template/withdraw/<int:template_id>/",
        template_maker_checker.template_withdraw_view,
        name="template_withdraw",
    ),
    # Template Checker URLs
    path(
        "checker/templates/pending/",
        template_maker_checker.template_checker_pending_list_view,
        name="template_checker_pending_list",
    ),
    path(
        "checker/template/review/<int:template_id>/",
        template_maker_checker.template_checker_review_view,
        name="template_checker_review",
    ),
    path(
        "checker/template/approve/<int:template_id>/",
        template_maker_checker.template_approve_view,
        name="template_approve",
    ),
    path(
        "checker/template/return/<int:template_id>/",
        template_maker_checker.template_return_view,
        name="template_return",
    ),
    # IFRS9 Template Maker URLs
    path(
        "maker/ifrs9/templates/drafts/",
        template_maker_checker.ifrs9_template_maker_draft_list_view,
        name="ifrs9_template_maker_draft_list",
    ),
    path(
        "maker/ifrs9/templates/submitted/",
        template_maker_checker.ifrs9_template_maker_submitted_list_view,
        name="ifrs9_template_maker_submitted_list",
    ),
    path(
        "maker/ifrs9/template/view/<int:template_id>/",
        template_maker_checker.ifrs9_template_maker_view,
        name="ifrs9_template_maker_view",
    ),
    path(
        "maker/ifrs9/template/submit/<int:template_id>/",
        template_maker_checker.ifrs9_template_submit_view,
        name="ifrs9_template_submit",
    ),
    path(
        "maker/ifrs9/template/withdraw/<int:template_id>/",
        template_maker_checker.ifrs9_template_withdraw_view,
        name="ifrs9_template_withdraw",
    ),
    # IFRS9 Template Checker URLs
    path(
        "checker/ifrs9/templates/pending/",
        template_maker_checker.ifrs9_template_checker_pending_list_view,
        name="ifrs9_template_checker_pending_list",
    ),
    path(
        "checker/ifrs9/template/review/<int:template_id>/",
        template_maker_checker.ifrs9_template_checker_review_view,
        name="ifrs9_template_checker_review",
    ),
    path(
        "checker/ifrs9/template/approve/<int:template_id>/",
        template_maker_checker.ifrs9_template_approve_view,
        name="ifrs9_template_approve",
    ),
    path(
        "checker/ifrs9/template/return/<int:template_id>/",
        template_maker_checker.ifrs9_template_return_view,
        name="ifrs9_template_return",
    ),
]

urlpatterns = _protect_urlpatterns(urlpatterns)
