# Generated by Django 5.1 on 2026-03-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial_pg"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_settings_user_roles", "Can view settings user roles"),
                    ("can_assign_settings_roles", "Can assign settings user roles"),
                ]
            },
        ),
    ]
