# Generated by Django 5.1 on 2026-03-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_settings_user_roles", "Can view settings user roles"),
                    ("can_assign_settings_roles", "Can assign settings user roles"),
                    ("can_view_settings_database", "Can view settings database configuration"),
                    ("can_manage_settings_database", "Can manage settings database configuration"),
                ]
            },
        ),
    ]
