# Generated by Django 5.1 on 2026-04-13 19:04

import django.db.models.deletion
from django.db import migrations, models


def seed_universal_settings_workspace(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    SystemModule = apps.get_model('Users', 'SystemModule')
    SystemSetting = apps.get_model('Users', 'SystemSetting')
    RoleModuleAccess = apps.get_model('Users', 'RoleModuleAccess')

    if not SystemSetting.objects.filter(singleton_id=1).exists():
        SystemSetting.objects.create(singleton_id=1)

    ifrs9_module, _ = SystemModule.objects.get_or_create(
        code='IFRS9',
        defaults={
            'name': 'IFRS 9',
            'route_name': 'ifrs9_home',
            'icon_class': 'fas fa-chart-line',
            'accent_class': 'ifrs9',
            'description': 'Credit risk, staging, ECL, and reporting',
            'is_active': True,
            'display_order': 10,
        },
    )

    for group in Group.objects.all():
        RoleModuleAccess.objects.get_or_create(
            group=group,
            module=ifrs9_module,
            defaults={'can_view': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_options_database_settings'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('route_name', models.CharField(max_length=120)),
                ('icon_class', models.CharField(blank=True, default='', max_length=120)),
                ('accent_class', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Module',
                'verbose_name_plural': 'System Modules',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('idle_timeout_minutes', models.PositiveSmallIntegerField(default=15)),
                ('absolute_session_timeout_minutes', models.PositiveSmallIntegerField(default=480)),
                ('default_landing_rule', models.CharField(choices=[('launcher', 'Always show module launcher'), ('direct_first_module', 'Open directly when only one module is available')], default='launcher', max_length=32)),
                ('failed_login_limit', models.PositiveSmallIntegerField(default=3)),
                ('lockout_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('enable_self_profile_edit', models.BooleanField(default=True)),
                ('enable_self_password_change', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='RoleModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_entries', to='auth.group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access_entries', to='Users.systemmodule')),
            ],
            options={
                'verbose_name': 'Role Module Access',
                'verbose_name_plural': 'Role Module Access',
                'unique_together': {('group', 'module')},
            },
        ),
        migrations.RunPython(seed_universal_settings_workspace, migrations.RunPython.noop),
    ]
