# Generated by Django 5.1 on 2026-04-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_add_microsoft_auth_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_auth_mode",
            field=models.CharField(
                choices=[
                    ("simulated", "Simulated mode (no tenant required)"),
                    ("live_entra", "Live Microsoft Entra mode"),
                ],
                default="simulated",
                max_length=24,
            ),
        ),
    ]
