# Generated by Django 5.1 on 2026-04-13 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0009_finalize_authenticator_only_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="password_expiry_days",
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="password_policy",
            field=models.CharField(
                choices=[
                    ("basic", "Basic: at least 8 characters"),
                    ("standard", "Standard: upper, lower, and number"),
                    ("strong", "Strong: 12+ chars with upper, lower, number, and special"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
