# Generated by Django 5.1 on 2026-04-14 11:05

from django.db import migrations, models
import django.db.models.deletion


def copy_role_access_to_users(apps, schema_editor):
    CustomUser = apps.get_model("Users", "CustomUser")
    RoleModuleAccess = apps.get_model("Users", "RoleModuleAccess")
    UserModuleAccess = apps.get_model("Users", "UserModuleAccess")

    rows_to_create = []
    seen = set()
    for user in CustomUser.objects.all().prefetch_related("groups"):
        group_ids = list(user.groups.values_list("id", flat=True))
        if not group_ids:
            continue
        for access in RoleModuleAccess.objects.filter(group_id__in=group_ids, can_view=True):
            key = (user.id, access.module_id)
            if key in seen:
                continue
            seen.add(key)
            rows_to_create.append(
                UserModuleAccess(
                    user_id=user.id,
                    module_id=access.module_id,
                    can_view=True,
                )
            )

    if rows_to_create:
        UserModuleAccess.objects.bulk_create(rows_to_create, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0012_alter_systemsetting_password_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModuleAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_view", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_access_entries", to="Users.systemmodule")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="module_access_entries", to="Users.customuser")),
            ],
            options={
                "verbose_name": "User Module Access",
                "verbose_name_plural": "User Module Access",
                "unique_together": {("user", "module")},
            },
        ),
        migrations.RunPython(copy_role_access_to_users, migrations.RunPython.noop),
    ]
