# Generated by Django 5.1 on 2026-04-16 21:35

from django.db import migrations


def seed_scorecard_module(apps, schema_editor):
    SystemModule = apps.get_model("Users", "SystemModule")
    SystemModule.objects.get_or_create(
        code="SCORECARD",
        defaults={
            "name": "Scorecard",
            "route_name": "scorecard:scorecard_dashboard",
            "icon_class": "fas fa-calculator",
            "accent_class": "scorecard",
            "description": "Scoring, score templates, and score operations",
            "is_active": True,
            "display_order": 20,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0013_add_user_module_access"),
    ]

    operations = [
        migrations.RunPython(seed_scorecard_module, migrations.RunPython.noop),
    ]
