# Generated by Codex on 2026-06-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0018_add_password_expiry_warning_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_name", models.CharField(default="Nexa Compliance", max_length=120)),
                ("version_number", models.CharField(max_length=40)),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("major", "Major release"),
                            ("minor", "Minor release"),
                            ("patch", "Patch"),
                            ("hotfix", "Hotfix"),
                        ],
                        default="patch",
                        max_length=20,
                    ),
                ),
                ("patch_reference", models.CharField(blank=True, default="", max_length=120)),
                ("build_number", models.CharField(blank=True, default="", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("deployed", "Deployed"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="deployed",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("deployed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("release_notes", models.TextField(blank=True, default="")),
                ("patches_applied", models.TextField(blank=True, default="")),
                ("rollback_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_application_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Version",
                "verbose_name_plural": "Application Versions",
                "ordering": ["-deployed_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["application_name", "version_number"],
                        name="unique_application_version_number",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="applicationversion",
            index=models.Index(
                fields=["application_name", "version_number"],
                name="Users_appli_applica_8d1901_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationversion",
            index=models.Index(
                fields=["status", "is_current"],
                name="Users_appli_status_3666d4_idx",
            ),
        ),
    ]
