# Generated by Django 5.1 on 2026-05-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("route_name", models.CharField(max_length=120)),
                (
                    "icon_class",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "accent_class",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Module",
                "verbose_name_plural": "System Modules",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idle_timeout_minutes", models.PositiveSmallIntegerField(default=15)),
                (
                    "absolute_session_timeout_minutes",
                    models.PositiveSmallIntegerField(default=480),
                ),
                (
                    "default_landing_rule",
                    models.CharField(
                        choices=[
                            ("launcher", "Always show module launcher"),
                            (
                                "direct_first_module",
                                "Open directly when only one module is available",
                            ),
                        ],
                        default="launcher",
                        max_length=32,
                    ),
                ),
                ("failed_login_limit", models.PositiveSmallIntegerField(default=3)),
                (
                    "lockout_duration_minutes",
                    models.PositiveSmallIntegerField(default=60),
                ),
                ("enable_self_profile_edit", models.BooleanField(default=True)),
                ("enable_self_password_change", models.BooleanField(default=True)),
                ("password_expiry_days", models.PositiveSmallIntegerField(default=90)),
                (
                    "password_expiry_warning_days",
                    models.PositiveSmallIntegerField(default=7),
                ),
                ("password_history_count", models.PositiveSmallIntegerField(default=5)),
                (
                    "password_policy",
                    models.CharField(
                        choices=[
                            ("basic", "Basic: no restrictions"),
                            ("minimum", "Minimum: at least 8 characters"),
                            ("standard", "Standard: upper, lower, and number"),
                            (
                                "strong",
                                "Strong: 12+ chars with upper, lower, number, and special",
                            ),
                            (
                                "enterprise",
                                "Enterprise: 14+ chars with upper, lower, number, and special",
                            ),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("enable_microsoft_authentication", models.BooleanField(default=False)),
                (
                    "microsoft_auth_mode",
                    models.CharField(
                        choices=[
                            ("simulated", "Microsoft Authenticator app (QR code)")
                        ],
                        default="simulated",
                        max_length=24,
                    ),
                ),
                ("microsoft_auth_on_login", models.BooleanField(default=True)),
                (
                    "microsoft_auth_on_password_change",
                    models.BooleanField(default=False),
                ),
                (
                    "microsoft_auth_enforce_periodically",
                    models.BooleanField(default=False),
                ),
                (
                    "microsoft_auth_recheck_days",
                    models.PositiveSmallIntegerField(default=30),
                ),
                (
                    "microsoft_tenant_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "microsoft_client_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "microsoft_redirect_uri",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("address", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=55)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                ("failed_login_attempts", models.PositiveSmallIntegerField(default=0)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
                (
                    "lock_immediately_on_next_failure",
                    models.BooleanField(default=False),
                ),
                ("permanently_locked", models.BooleanField(default=False)),
                (
                    "microsoft_authenticator_secret",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("microsoft_authenticator_enabled", models.BooleanField(default=False)),
                (
                    "microsoft_authenticator_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="customuser_groups",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="customuser_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_view_settings_user_roles", "Can view settings user roles"),
                    ("can_assign_settings_roles", "Can assign settings user roles"),
                    (
                        "can_view_settings_database",
                        "Can view settings database configuration",
                    ),
                    (
                        "can_manage_settings_database",
                        "Can manage settings database configuration",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                (
                    "login_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "session_duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "end_reason",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("manual_logout", "Manual Sign Out"),
                            ("idle_timeout", "Idle Timeout"),
                            ("absolute_timeout", "Maximum Session Timeout"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Access Log",
                "verbose_name_plural": "User Access Logs",
                "ordering": ["-login_time", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password History",
                "verbose_name_plural": "Password History",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                ("change_description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "db_table": "audit_trail",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RoleModuleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_access_entries",
                        to="auth.group",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_access_entries",
                        to="Users.systemmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Module Access",
                "verbose_name_plural": "Role Module Access",
                "unique_together": {("group", "module")},
            },
        ),
        migrations.CreateModel(
            name="UserModuleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_access_entries",
                        to="Users.systemmodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_access_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Module Access",
                "verbose_name_plural": "User Module Access",
                "unique_together": {("user", "module")},
            },
        ),
    ]
