# Generated by Django 5.1 on 2026-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_add_universal_settings_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="enable_microsoft_authentication",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_auth_enforce_periodically",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_auth_on_login",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_auth_on_password_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_auth_recheck_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_client_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_redirect_uri",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="microsoft_tenant_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
