# Generated by Django 5.1 on 2026-04-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_add_microsoft_auth_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="microsoft_authenticator_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="microsoft_authenticator_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="microsoft_authenticator_secret",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
