# Generated by Django 5.1 on 2026-04-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_add_user_authenticator_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="microsoft_auth_mode",
            field=models.CharField(
                choices=[
                    ("simulated", "Microsoft Authenticator app (QR code)"),
                    ("live_entra", "Live Microsoft Entra mode"),
                ],
                default="simulated",
                max_length=24,
            ),
        ),
    ]
