# Generated by Django 5.1 on 2026-04-13 23:55

from django.db import migrations, models


def normalize_authenticator_mode(apps, schema_editor):
    SystemSetting = apps.get_model("Users", "SystemSetting")
    SystemSetting.objects.update(
        microsoft_auth_mode="simulated",
        microsoft_tenant_id="",
        microsoft_client_id="",
        microsoft_redirect_uri="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_systemsetting_microsoft_auth_mode"),
    ]

    operations = [
        migrations.RunPython(normalize_authenticator_mode, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="systemsetting",
            name="microsoft_auth_mode",
            field=models.CharField(
                choices=[("simulated", "Microsoft Authenticator app (QR code)")],
                default="simulated",
                max_length=24,
            ),
        ),
    ]
