# Generated by Django 5.1 on 2026-04-14 00:15

from django.db import migrations, models


def seed_current_password_history(apps, schema_editor):
    CustomUser = apps.get_model("Users", "CustomUser")
    PasswordHistory = apps.get_model("Users", "PasswordHistory")

    history_rows = []
    for user in CustomUser.objects.exclude(password="").only("id", "password"):
        history_rows.append(
            PasswordHistory(
                user_id=user.id,
                password_hash=user.password,
            )
        )

    if history_rows:
        PasswordHistory.objects.bulk_create(history_rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0008_add_password_policy_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="password_history_count",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="password_history_entries",
                        to="Users.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password History",
                "verbose_name_plural": "Password History",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.RunPython(seed_current_password_history, migrations.RunPython.noop),
    ]
