# Generated by Django 5.1 on 2026-04-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0009_add_password_history_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="password_policy",
            field=models.CharField(
                choices=[
                    ("basic", "Basic: no restrictions"),
                    ("minimum", "Minimum: at least 8 characters"),
                    ("standard", "Standard: upper, lower, and number"),
                    ("strong", "Strong: 12+ chars with upper, lower, number, and special"),
                    ("enterprise", "Enterprise: 14+ chars with upper, lower, number, and special"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
