# Generated by Django 5.1 on 2026-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0015_add_permanent_lock_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="password_expiry_warning_days",
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
