# Generated by Django 5.1 on 2026-07-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_add_application_version'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationversion',
            new_name='Users_appli_applica_4c58fe_idx',
            old_name='Users_appli_applica_8d1901_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationversion',
            new_name='Users_appli_status_6c2bd2_idx',
            old_name='Users_appli_status_3666d4_idx',
        ),
    ]
