# Generated by Codex on 2026-10-01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0019_rename_users_appli_applica_8d1901_idx_users_appli_applica_4c58fe_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="inactivity_lock_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="inactivity_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="enable_inactivity_lock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="inactivity_lock_days",
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AlterField(
            model_name="useraccesslog",
            name="end_reason",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("manual_logout", "Manual Sign Out"),
                    ("idle_timeout", "Idle Timeout"),
                    ("absolute_timeout", "Maximum Session Timeout"),
                    ("inactivity_lock", "Account Inactivity Lock"),
                ],
                db_index=True,
                default="active",
                max_length=32,
            ),
        ),
    ]
